import {
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_TITLE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Dashboard',
        translateKey: 'Dashboard',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'workspaces',
        path: '/workspaces',
        title: 'Workspaces',
        translateKey: 'Workspaces',
        icon: 'workspaces',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'financeSection',
        path: '',
        title: 'Finanzas',
        translateKey: 'Finanzas',
        icon: 'finance',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'finance.accounts',
                path: '/finance/accounts',
                title: 'Cuentas',
                translateKey: 'Cuentas',
                icon: 'accounts',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'finance.categories',
                path: '/finance/categories',
                title: 'Categorías',
                translateKey: 'Categorías',
                icon: 'categories',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'finance.transactions',
                path: '/finance/transactions',
                title: 'Movimientos',
                translateKey: 'Movimientos',
                icon: 'transactions',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'finance.transfers',
                path: '/finance/transfers',
                title: 'Transferencias',
                translateKey: 'Transferencias',
                icon: 'transfers',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'budgets',
        path: '/budgets',
        title: 'Presupuestos',
        translateKey: 'Presupuestos',
        icon: 'budgets',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'goals',
        path: '/goals',
        title: 'Metas',
        translateKey: 'Metas',
        icon: 'goals',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'reportsSection',
        path: '',
        title: 'Reportes',
        translateKey: 'Reportes',
        icon: 'reports',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'reports.byCategory',
                path: '/reports/by-category',
                title: 'Por categoría',
                translateKey: 'Por categoría',
                icon: 'reportByCategory',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'reports.cashflow',
                path: '/reports/cashflow',
                title: 'Cashflow',
                translateKey: 'Cashflow',
                icon: 'reportCashflow',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
